### ISSUE TITLE
Performance improvement: no waiting to check capability overwriting

### ISSUE THREAD

**Issue by jasonyu1996** [jasonyu1996/capstone-gem5#7]
The current implementation uses `rd` also as a source register in order to check whether it is a capability to update refcounts accordingly. We can instead just do that when a physical register gets unmapped.

**Comment by jasonyu1996** [comment]
Examples:

```
ldc ca0, ca1
movc ca0, ca2
```

The second instruction `movc` does not need to wait for the value of `ca0` to be ready. Instead, when the result of `ldc` is ready, we can just check whether its value of `ca0` has already been overwritten (mapped to a different physical register), and update (or skip updating) the refcounts accordingly.

**Comment by hakase56557** [comment]
Initial changes submitted in: 790d74e00dae462bf82aa6c1a3a80cd2d705703a
This version needs to be updated to also actually update the refcounts

**Comment by jasonyu1996** [comment]
> Initial changes submitted in: [790d74e](https://github.com/project-starch/capstone-gem5/commit/790d74e00dae462bf82aa6c1a3a80cd2d705703a) This version needs to be updated to also actually update the refcounts

Coool. BTW you can do fancy stuff like using `#n` to reference issue number n in the commit message.
